.TH Adonthell 6
.SH NAME
Adonthell \- a Free Role Playing Game engine.
.SH SYNOPSIS
.B adonthell
.I "[options] files ..."
.SH "DESCRIPTION"
.BR Adonthell
is a Free graphical role playing game engine.
.BR
This program is used to run
.BR Adonthell
games - therefore you need one game installed in order to play
something.
.SH OPTIONS
.TP
.B \-h,
Print help message.
.TP
.B \-v,
Print version and exit.
.TP
.B \-d,
Print the data directory and exit (for developers).
.TP
.B \-l,
List installed games and exit.
.TP
.B \-g
.I dir
, play the game contained in
.I dir
(for developers).
.TP
.B \-c,
Byte-compile all Python scripts in this directory (for developers).

.SH AUTHOR
This manual page was written by Alexandre Courbot <alexandrecourbot@linuxgames.com>,
for the Debian GNU/Linux system (but may be used by others).
