/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.10u-20020107-1133
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif



#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);

typedef struct swig_type_info {
  const char             *name;                 
  swig_converter_func     converter;
  const char             *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
  void                   *clientdata;	
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
SWIGEXPORT(swig_type_info *) SWIG_TypeQuery(const char *);
SWIGEXPORT(void) SWIG_TypeClientData(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* Set the clientdata field for a type */
SWIGRUNTIME(void)
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = swig_type_list;
      while (tc) {
	if ((strcmp(tc->name, equiv->name) == 0))
	  SWIG_TypeClientData(tc,clientdata);
	tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}
#endif

#ifdef __cplusplus
}
#endif




/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4
#define SWIG_PY_BINARY  5

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(int)               SWIG_ConvertPacked(PyObject *, void *, int sz, swig_type_info *, int);
SWIGEXPORT(char *)            SWIG_PackData(char *c, void *, int);
SWIGEXPORT(char *)            SWIG_UnpackData(char *c, void *, int);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *,int own);
SWIGEXPORT(PyObject *)        SWIG_NewPackedObj(void *, int sz, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);
SWIGEXPORT(PyObject *)        SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own);
#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  (char *)"swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}

/* Pack binary data into a string */
SWIGRUNTIME(char *)
SWIG_PackData(char *c, void *ptr, int sz) {
  static char hex[17] = "0123456789abcdef";
  int i;
  unsigned char *u = (unsigned char *) ptr;
  register unsigned char uu;
  for (i = 0; i < sz; i++,u++) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* Unpack binary data from a string */
SWIGRUNTIME(char *)
SWIG_UnpackData(char *c, void *ptr, int sz) {
  register unsigned char uu;
  register int d;
  unsigned char *u = (unsigned char *) ptr;
  int i;
  for (i = 0; i < sz; i++, u++) {
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    *u = uu;
  }
  return c;
}

/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj) return 0;
  if (obj == Py_None) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  c = SWIG_UnpackData(c,ptr,sizeof(void *));
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*) *ptr);
  }
  return 0;

type_error:
  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Convert a packed value value */
SWIGRUNTIME(int)
SWIG_ConvertPacked(PyObject *obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  char  *c;

  if ((!obj) || (!PyString_Check(obj))) goto type_error;
  c = PyString_AsString(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c,ptr,sz);
  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type, int own) {
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, (char *) type->name, NULL);
#else
  {
    char result[512];
    char *r = result;
    *(r++) = '_';
    r = SWIG_PackData(r,&ptr,sizeof(void *));
    strcpy(r,type->name);
    robj = PyString_FromString(result);
  }
#endif
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyObject *inst;
    PyObject *args = Py_BuildValue((char*)"(O)", robj);
    Py_DECREF(robj);
    inst = PyObject_CallObject((PyObject *) type->clientdata, args);
    Py_DECREF(args);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString(inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = inst;
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_MakeShadow(PyObject *robj, swig_type_info *type, int own) {
  if (!robj || (robj == Py_None)) return robj;
  if (type->clientdata) {
    PyInstanceObject *inst;
    inst = PyObject_NEW(PyInstanceObject, &PyInstance_Type);
    if (!inst) return robj;
    inst->in_dict = PyDict_New();
    inst->in_class = (PyClassObject *) type->clientdata;
    Py_INCREF(inst->in_class);
    PyObject_SetAttrString((PyObject *)inst,(char*)"this",robj);
    Py_DECREF(robj);
    if (own) {
      PyObject *n = PyInt_FromLong(1);
      PyObject_SetAttrString((PyObject *)inst,(char*)"thisown",n);
      Py_DECREF(n);
    }
    robj = (PyObject *) inst;
    Py_INCREF(robj);
  }
  return robj;
}

SWIGRUNTIME(PyObject *)
SWIG_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  strcpy(r,type->name);
  return PyString_FromString(result);
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype,0);
      break;
    case SWIG_PY_BINARY:
      obj = SWIG_NewPackedObj(constants[i].pvalue, constants[i].lvalue, *(constants[i].ptype));
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif








/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_igzstream swig_types[0] 
#define  SWIGTYPE_p_ogzstream swig_types[1] 
#define  SWIGTYPE_p_character_base swig_types[2] 
#define  SWIGTYPE_p_storage swig_types[3] 
#define  SWIGTYPE_p_pairTstring_signed_int_t swig_types[4] 
#define  SWIGTYPE_p_objects swig_types[5] 
#define  SWIGTYPE_p_item_base swig_types[6] 
static swig_type_info *swig_types[8];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= itemtestc.so
  ------------------------------------------------*/
#define SWIG_init    inititemtestc

#define SWIG_name    "itemtestc"

#include <string>
#include "types.h"
#include "storage.h"
#include "character_base.h"
#include "item_base.h"

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_new_storage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    storage *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_storage")) return NULL;
    result = (storage *)new storage();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_storage, 1);
    return resultobj;
}


static PyObject *_wrap_delete_storage(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    storage *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_storage",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_storage,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_storage_set_val(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    storage *arg1 ;
    string arg2 ;
    int arg3 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOi:storage_set_val",&obj0,&obj1,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_storage,1)) == -1) return NULL;
    {
        if (PyString_Check (obj1))
        {
            arg2 = string (PyString_AsString(obj1));
        }
        else
        {
            PyErr_SetString (PyExc_TypeError, "not a String");
            return NULL;
        }
    }
    (arg1)->set_val(arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_storage_get_val(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    storage *arg1 ;
    string arg2 ;
    int result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:storage_get_val",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_storage,1)) == -1) return NULL;
    {
        if (PyString_Check (obj1))
        {
            arg2 = string (PyString_AsString(obj1));
        }
        else
        {
            PyErr_SetString (PyExc_TypeError, "not a String");
            return NULL;
        }
    }
    result = (int )(arg1)->get_val(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_storage_next(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    storage *arg1 ;
    pair<string,signed int > result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:storage_next",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_storage,1)) == -1) return NULL;
    result = (arg1)->next();
    
    {
        pair<string,signed int > * resultptr;
        resultptr = new pair<string,signed int > (result);
        resultobj = SWIG_NewPointerObj((void *) resultptr, SWIGTYPE_p_pairTstring_signed_int_t, 1);
    }
    return resultobj;
}


static PyObject * storage_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_storage, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_new_objects(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    objects *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_objects")) return NULL;
    result = (objects *)new objects();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_objects, 1);
    return resultobj;
}


static PyObject *_wrap_objects_set_val(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    objects *arg1 ;
    char *arg2 ;
    storage *arg3 ;
    PyObject * obj0  = 0 ;
    PyObject * obj2  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OsO:objects_set_val",&obj0,&arg2,&obj2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_objects,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj2,(void **) &arg3, SWIGTYPE_p_storage,1)) == -1) return NULL;
    (arg1)->set_val((char const *)arg2,arg3);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_objects_get_val(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    objects *arg1 ;
    char *arg2 ;
    storage *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:objects_get_val",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_objects,1)) == -1) return NULL;
    result = (storage *)(arg1)->get_val((char const *)arg2);
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_storage, 0);
    return resultobj;
}


static PyObject *_wrap_objects_erase(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    objects *arg1 ;
    char *arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Os:objects_erase",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_objects,1)) == -1) return NULL;
    (arg1)->erase((char const *)arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_objects_next(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    objects *arg1 ;
    storage *result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:objects_next",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_objects,1)) == -1) return NULL;
    result = (storage *)(arg1)->next();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_storage, 0);
    return resultobj;
}


static PyObject *_wrap_delete_objects(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    objects *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_objects",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_objects,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * objects_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_objects, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_new_character_base(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_character_base")) return NULL;
    result = (character_base *)new character_base();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_character_base, 1);
    return resultobj;
}


static PyObject *_wrap_delete_character_base(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_character_base",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_character_base_get_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    string result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:character_base_get_name",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    result = ((character_base const *)arg1)->get_name();
    
    {
        resultobj = PyString_FromString((const char *)result.c_str()); 
    }
    return resultobj;
}


static PyObject *_wrap_character_base_get_id(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    string result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:character_base_get_id",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    result = (arg1)->get_id();
    
    {
        resultobj = PyString_FromString((const char *)result.c_str()); 
    }
    return resultobj;
}


static PyObject *_wrap_character_base_set_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    string arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:character_base_set_name",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    {
        if (PyString_Check (obj1))
        {
            arg2 = string (PyString_AsString(obj1));
        }
        else
        {
            PyErr_SetString (PyExc_TypeError, "not a String");
            return NULL;
        }
    }
    (arg1)->set_name(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_character_base_get_color(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    unsigned int result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:character_base_get_color",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    result = (unsigned int )((character_base const *)arg1)->get_color();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_character_base_set_color(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:character_base_set_color",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    (arg1)->set_color(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_character_base_get_portrait(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    string result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:character_base_get_portrait",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    result = ((character_base const *)arg1)->get_portrait();
    
    {
        resultobj = PyString_FromString((const char *)result.c_str()); 
    }
    return resultobj;
}


static PyObject *_wrap_character_base_set_portrait(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    string arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:character_base_set_portrait",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    {
        if (PyString_Check (obj1))
        {
            arg2 = string (PyString_AsString(obj1));
        }
        else
        {
            PyErr_SetString (PyExc_TypeError, "not a String");
            return NULL;
        }
    }
    (arg1)->set_portrait(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_character_base_get_dialogue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    string result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:character_base_get_dialogue",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    result = ((character_base const *)arg1)->get_dialogue();
    
    {
        resultobj = PyString_FromString((const char *)result.c_str()); 
    }
    return resultobj;
}


static PyObject *_wrap_character_base_set_dialogue(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    string arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:character_base_set_dialogue",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    {
        if (PyString_Check (obj1))
        {
            arg2 = string (PyString_AsString(obj1));
        }
        else
        {
            PyErr_SetString (PyExc_TypeError, "not a String");
            return NULL;
        }
    }
    (arg1)->set_dialogue(arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_character_base_get_state(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    igzstream *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:character_base_get_state",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_igzstream,1)) == -1) return NULL;
    (arg1)->get_state(*arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_character_base_put_state(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    character_base *arg1 ;
    ogzstream *arg2 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:character_base_put_state",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_ogzstream,1)) == -1) return NULL;
    (arg1)->put_state(*arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * character_base_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_character_base, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyObject *_wrap_new_item_base(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *result;
    
    if(!PyArg_ParseTuple(args,(char *)":new_item_base")) return NULL;
    result = (item_base *)new item_base();
    
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_item_base, 1);
    return resultobj;
}


static PyObject *_wrap_delete_item_base(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:delete_item_base",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    delete arg1;
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_item_base_init(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    string arg2 ;
    string arg3 ;
    string arg4 ;
    unsigned short arg5 ;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    PyObject * obj2  = 0 ;
    PyObject * obj3  = 0 ;
    PyObject * obj4  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OOOOO:item_base_init",&obj0,&obj1,&obj2,&obj3,&obj4)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    {
        if (PyString_Check (obj1))
        {
            arg2 = string (PyString_AsString(obj1));
        }
        else
        {
            PyErr_SetString (PyExc_TypeError, "not a String");
            return NULL;
        }
    }
    {
        if (PyString_Check (obj2))
        {
            arg3 = string (PyString_AsString(obj2));
        }
        else
        {
            PyErr_SetString (PyExc_TypeError, "not a String");
            return NULL;
        }
    }
    {
        if (PyString_Check (obj3))
        {
            arg4 = string (PyString_AsString(obj3));
        }
        else
        {
            PyErr_SetString (PyExc_TypeError, "not a String");
            return NULL;
        }
    }
    arg5 = (unsigned short ) PyInt_AsLong(obj4);
    if (PyErr_Occurred()) return NULL;
    (arg1)->init(arg2,arg3,arg4,arg5);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_item_base_get_name(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    string result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:item_base_get_name",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    result = ((item_base const *)arg1)->get_name();
    
    {
        resultobj = PyString_FromString((const char *)result.c_str()); 
    }
    return resultobj;
}


static PyObject *_wrap_item_base_get_description(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    string result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:item_base_get_description",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    result = ((item_base const *)arg1)->get_description();
    
    {
        resultobj = PyString_FromString((const char *)result.c_str()); 
    }
    return resultobj;
}


static PyObject *_wrap_item_base_equip(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    character_base *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:item_base_equip",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_character_base,1)) == -1) return NULL;
    result = (bool )(arg1)->equip(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_item_base_combine(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    item_base *arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    PyObject * obj1  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"OO:item_base_combine",&obj0,&obj1)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(obj1,(void **) &arg2, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    result = (bool )(arg1)->combine(arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_item_base_use(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"O:item_base_use",&obj0)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    result = (bool )(arg1)->use();
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_item_base_has_ability(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    int arg2 ;
    bool result;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:item_base_has_ability",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    result = (bool )(arg1)->has_ability((action )arg2);
    
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_item_base_set_ability(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    item_base *arg1 ;
    int arg2 ;
    PyObject * obj0  = 0 ;
    
    if(!PyArg_ParseTuple(args,(char *)"Oi:item_base_set_ability",&obj0,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(obj0,(void **) &arg1, SWIGTYPE_p_item_base,1)) == -1) return NULL;
    (arg1)->set_ability((action )arg2);
    
    Py_INCREF(Py_None); resultobj = Py_None;
    return resultobj;
}


static PyObject * item_base_swigregister(PyObject *self, PyObject *args) {
    PyObject *obj;
    if (!PyArg_ParseTuple(args,(char*)"O", &obj)) return NULL;
    SWIG_TypeClientData(SWIGTYPE_p_item_base, obj);
    Py_INCREF(obj);
    return Py_BuildValue((char *)"");
}
static PyMethodDef SwigMethods[] = {
	 { (char *)"new_storage", _wrap_new_storage, METH_VARARGS },
	 { (char *)"delete_storage", _wrap_delete_storage, METH_VARARGS },
	 { (char *)"storage_set_val", _wrap_storage_set_val, METH_VARARGS },
	 { (char *)"storage_get_val", _wrap_storage_get_val, METH_VARARGS },
	 { (char *)"storage_next", _wrap_storage_next, METH_VARARGS },
	 { (char *)"storage_swigregister", storage_swigregister, METH_VARARGS },
	 { (char *)"new_objects", _wrap_new_objects, METH_VARARGS },
	 { (char *)"objects_set_val", _wrap_objects_set_val, METH_VARARGS },
	 { (char *)"objects_get_val", _wrap_objects_get_val, METH_VARARGS },
	 { (char *)"objects_erase", _wrap_objects_erase, METH_VARARGS },
	 { (char *)"objects_next", _wrap_objects_next, METH_VARARGS },
	 { (char *)"delete_objects", _wrap_delete_objects, METH_VARARGS },
	 { (char *)"objects_swigregister", objects_swigregister, METH_VARARGS },
	 { (char *)"new_character_base", _wrap_new_character_base, METH_VARARGS },
	 { (char *)"delete_character_base", _wrap_delete_character_base, METH_VARARGS },
	 { (char *)"character_base_get_name", _wrap_character_base_get_name, METH_VARARGS },
	 { (char *)"character_base_get_id", _wrap_character_base_get_id, METH_VARARGS },
	 { (char *)"character_base_set_name", _wrap_character_base_set_name, METH_VARARGS },
	 { (char *)"character_base_get_color", _wrap_character_base_get_color, METH_VARARGS },
	 { (char *)"character_base_set_color", _wrap_character_base_set_color, METH_VARARGS },
	 { (char *)"character_base_get_portrait", _wrap_character_base_get_portrait, METH_VARARGS },
	 { (char *)"character_base_set_portrait", _wrap_character_base_set_portrait, METH_VARARGS },
	 { (char *)"character_base_get_dialogue", _wrap_character_base_get_dialogue, METH_VARARGS },
	 { (char *)"character_base_set_dialogue", _wrap_character_base_set_dialogue, METH_VARARGS },
	 { (char *)"character_base_get_state", _wrap_character_base_get_state, METH_VARARGS },
	 { (char *)"character_base_put_state", _wrap_character_base_put_state, METH_VARARGS },
	 { (char *)"character_base_swigregister", character_base_swigregister, METH_VARARGS },
	 { (char *)"new_item_base", _wrap_new_item_base, METH_VARARGS },
	 { (char *)"delete_item_base", _wrap_delete_item_base, METH_VARARGS },
	 { (char *)"item_base_init", _wrap_item_base_init, METH_VARARGS },
	 { (char *)"item_base_get_name", _wrap_item_base_get_name, METH_VARARGS },
	 { (char *)"item_base_get_description", _wrap_item_base_get_description, METH_VARARGS },
	 { (char *)"item_base_equip", _wrap_item_base_equip, METH_VARARGS },
	 { (char *)"item_base_combine", _wrap_item_base_combine, METH_VARARGS },
	 { (char *)"item_base_use", _wrap_item_base_use, METH_VARARGS },
	 { (char *)"item_base_has_ability", _wrap_item_base_has_ability, METH_VARARGS },
	 { (char *)"item_base_set_ability", _wrap_item_base_set_ability, METH_VARARGS },
	 { (char *)"item_base_swigregister", item_base_swigregister, METH_VARARGS },
	 { NULL, NULL }
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static void *_p_character_baseTo_p_storage(void *x) {
    return (void *)((storage *) ((character_base *) x));
}
static void *_p_item_baseTo_p_storage(void *x) {
    return (void *)((storage *) ((item_base *) x));
}
static swig_type_info _swigt__p_igzstream[] = {{"_p_igzstream", 0, "igzstream *"},{"_p_igzstream"},{0}};
static swig_type_info _swigt__p_ogzstream[] = {{"_p_ogzstream", 0, "ogzstream *"},{"_p_ogzstream"},{0}};
static swig_type_info _swigt__p_character_base[] = {{"_p_character_base", 0, "character_base *"},{"_p_character_base"},{0}};
static swig_type_info _swigt__p_storage[] = {{"_p_storage", 0, "storage *"},{"_p_character_base", _p_character_baseTo_p_storage},{"_p_storage"},{"_p_item_base", _p_item_baseTo_p_storage},{0}};
static swig_type_info _swigt__p_pairTstring_signed_int_t[] = {{"_p_pairTstring_signed_int_t", 0, "pair<string,signed int > *"},{"_p_pairTstring_signed_int_t"},{0}};
static swig_type_info _swigt__p_objects[] = {{"_p_objects", 0, "objects *"},{"_p_objects"},{0}};
static swig_type_info _swigt__p_item_base[] = {{"_p_item_base", 0, "item_base *"},{"_p_item_base"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_igzstream, 
_swigt__p_ogzstream, 
_swigt__p_character_base, 
_swigt__p_storage, 
_swigt__p_pairTstring_signed_int_t, 
_swigt__p_objects, 
_swigt__p_item_base, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
{ SWIG_PY_STRING,  (char*)"DIALOG_DIR", 0, 0, (void *)"dialogues/", 0},
{ SWIG_PY_INT,     (char *)"DWARF", (long) DWARF, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ELF", (long) ELF, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"HALFELF", (long) HALFELF, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"HUMAN", (long) HUMAN, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"FEMALE", (long) FEMALE, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"MALE", (long) MALE, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"NPC", (long) NPC, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PLAYER", (long) PLAYER, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"PARTY", (long) PARTY, 0, 0, 0},
{ SWIG_PY_STRING,  (char*)"ACTION_DIR", 0, 0, (void *)"", 0},
{ SWIG_PY_INT,     (char *)"EQUIP", (long) EQUIP, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"COMBINE", (long) COMBINE, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"USE", (long) USE, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"ENCHANT", (long) ENCHANT, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"BOOK", (long) 1, 0, 0, 0},
{ SWIG_PY_INT,     (char *)"WEAPON", (long) 2, 0, 0, 0},
{0}};

#ifdef __cplusplus
}
#endif

#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) SWIG_init(void) {
    static PyObject *SWIG_globals = 0;
    PyObject *m, *d;
    int       i;
    SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule((char *) SWIG_name, SwigMethods);
    d = PyModule_GetDict(m);
    
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    SWIG_InstallConstants(d,swig_const_table);
    
}

