/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3u-20001014-1904 (Alpha 5)
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct swig_type_info {
  char  *name;                 
  void *(*converter)(void *);
  char  *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(void *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

#endif

#ifdef __cplusplus
}
#endif



/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(void)              SWIG_MakePtr(char *c, void *, swig_type_info *);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  "swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}
/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  unsigned long p;
  register int d;
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj || (obj == Py_None)) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  /* Extract hex value from pointer */
  while ((d = *c)) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*)p);
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Take a pointer and convert it to a string */
SWIGRUNTIME(void) 
SWIG_MakePtr(char *c, void *ptr, swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[32], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type) {
  char result[512];
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, type->name, NULL);
#else
  SWIG_MakePtr(result,ptr,type);
  robj = PyString_FromString(result);
#endif
  return robj;
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype);
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif



/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_event_handler swig_types[0] 
#define  SWIGTYPE_p_leave_event swig_types[1] 
#define  SWIGTYPE_p_time_event swig_types[2] 
#define  SWIGTYPE_p_event swig_types[3] 
#define  SWIGTYPE_p_base_map_event swig_types[4] 
#define  SWIGTYPE_p_enter_event swig_types[5] 
#define  SWIGTYPE_p_vector_event__ swig_types[6] 
#define  SWIGTYPE_p_gzFile swig_types[7] 
#define  SWIGTYPE_p_mapcharacter swig_types[8] 
#define  SWIGTYPE_p_event_list swig_types[9] 
static swig_type_info *swig_types[11];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= eventc.so
  ------------------------------------------------*/
#define SWIG_init    initeventc

#define SWIG_name    "eventc"


#include "event.h"

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_event_script_file_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Os:event_script_file_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event,1)) == -1) return NULL;
    arg0->script_file = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_event_script_file_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event *arg0 ;
    PyObject * argo0 =0 ;
    char *result ;
    
    if(!PyArg_ParseTuple(args,"O:event_script_file_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event,1)) == -1) return NULL;
    result = (char *) (arg0->script_file);
    resultobj = PyString_FromString(result);
    return resultobj;
}


static PyObject *_wrap_event_save(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event *arg0 ;
    gzFile *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:event_save",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_gzFile,1)) == -1) return NULL;
    arg0->save(*arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_delete_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_event",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_base_map_event_save(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    gzFile *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:base_map_event_save",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_gzFile,1)) == -1) return NULL;
    arg0->save(*arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_base_map_event_submap_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    long arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ol:base_map_event_submap_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    arg0->submap = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_base_map_event_submap_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    PyObject * argo0 =0 ;
    long result ;
    
    if(!PyArg_ParseTuple(args,"O:base_map_event_submap_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    result = (long ) (arg0->submap);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_base_map_event_x_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    long arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ol:base_map_event_x_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    arg0->x = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_base_map_event_x_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    PyObject * argo0 =0 ;
    long result ;
    
    if(!PyArg_ParseTuple(args,"O:base_map_event_x_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    result = (long ) (arg0->x);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_base_map_event_y_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    long arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ol:base_map_event_y_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    arg0->y = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_base_map_event_y_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    PyObject * argo0 =0 ;
    long result ;
    
    if(!PyArg_ParseTuple(args,"O:base_map_event_y_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    result = (long ) (arg0->y);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_base_map_event_dir_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    signed char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:base_map_event_dir_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    arg0->dir = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_base_map_event_dir_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    PyObject * argo0 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"O:base_map_event_dir_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    result = (signed char ) (arg0->dir);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_base_map_event_map_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    long arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ol:base_map_event_map_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    arg0->map = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_base_map_event_map_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    PyObject * argo0 =0 ;
    long result ;
    
    if(!PyArg_ParseTuple(args,"O:base_map_event_map_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    result = (long ) (arg0->map);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_base_map_event_c_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    mapcharacter *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:base_map_event_c_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->c = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_base_map_event_c_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    PyObject * argo0 =0 ;
    mapcharacter *result ;
    
    if(!PyArg_ParseTuple(args,"O:base_map_event_c_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    result = (mapcharacter *) (arg0->c);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_mapcharacter);
    return resultobj;
}


static PyObject *_wrap_new_base_map_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *result ;
    
    if(!PyArg_ParseTuple(args,":new_base_map_event")) return NULL;
    result = (base_map_event *)new base_map_event();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_base_map_event);
    return resultobj;
}


static PyObject *_wrap_delete_base_map_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    base_map_event *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_base_map_event",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_base_map_event,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_new_enter_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    enter_event *result ;
    
    if(!PyArg_ParseTuple(args,":new_enter_event")) return NULL;
    result = (enter_event *)new enter_event();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_enter_event);
    return resultobj;
}


static PyObject *_wrap_delete_enter_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    enter_event *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_enter_event",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_enter_event,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_new_leave_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    leave_event *result ;
    
    if(!PyArg_ParseTuple(args,":new_leave_event")) return NULL;
    result = (leave_event *)new leave_event();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_leave_event);
    return resultobj;
}


static PyObject *_wrap_delete_leave_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    leave_event *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_leave_event",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_leave_event,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_new_time_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *result ;
    
    if(!PyArg_ParseTuple(args,":new_time_event")) return NULL;
    result = (time_event *)new time_event();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_time_event);
    return resultobj;
}


static PyObject *_wrap_time_event_save(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    gzFile *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:time_event_save",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_gzFile,1)) == -1) return NULL;
    arg0->save(*arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_time_event_minute_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    unsigned char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:time_event_minute_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    arg0->minute = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_time_event_minute_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    PyObject * argo0 =0 ;
    unsigned char result ;
    
    if(!PyArg_ParseTuple(args,"O:time_event_minute_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    result = (unsigned char ) (arg0->minute);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_time_event_m_step_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    unsigned char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:time_event_m_step_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    arg0->m_step = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_time_event_m_step_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    PyObject * argo0 =0 ;
    unsigned char result ;
    
    if(!PyArg_ParseTuple(args,"O:time_event_m_step_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    result = (unsigned char ) (arg0->m_step);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_time_event_hour_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    unsigned char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:time_event_hour_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    arg0->hour = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_time_event_hour_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    PyObject * argo0 =0 ;
    unsigned char result ;
    
    if(!PyArg_ParseTuple(args,"O:time_event_hour_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    result = (unsigned char ) (arg0->hour);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_time_event_h_step_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    unsigned char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:time_event_h_step_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    arg0->h_step = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_time_event_h_step_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    PyObject * argo0 =0 ;
    unsigned char result ;
    
    if(!PyArg_ParseTuple(args,"O:time_event_h_step_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    result = (unsigned char ) (arg0->h_step);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_time_event_day_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    unsigned char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:time_event_day_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    arg0->day = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_time_event_day_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    PyObject * argo0 =0 ;
    unsigned char result ;
    
    if(!PyArg_ParseTuple(args,"O:time_event_day_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    result = (unsigned char ) (arg0->day);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_time_event_d_step_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    unsigned char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:time_event_d_step_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    arg0->d_step = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_time_event_d_step_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    PyObject * argo0 =0 ;
    unsigned char result ;
    
    if(!PyArg_ParseTuple(args,"O:time_event_d_step_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    result = (unsigned char ) (arg0->d_step);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_time_event_time_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    unsigned long arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ol:time_event_time_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    arg0->time = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_time_event_time_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    PyObject * argo0 =0 ;
    unsigned long result ;
    
    if(!PyArg_ParseTuple(args,"O:time_event_time_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    result = (unsigned long ) (arg0->time);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_delete_time_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    time_event *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_time_event",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_time_event,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_delete_event_list(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event_list *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_event_list",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event_list,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_event_list_add_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event_list *arg0 ;
    event *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:event_list_add_event",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event_list,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_event,1)) == -1) return NULL;
    arg0->add_event(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_event_list_add_map_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event_list *arg0 ;
    char *arg1 ;
    unsigned short arg2 ;
    long arg3 = -1 ;
    long arg4 = -1 ;
    long arg5 = -1 ;
    short arg6 = -1 ;
    mapcharacter *arg7 = NULL ;
    PyObject * argo0 =0 ;
    PyObject * argo7 =0 ;
    
    if(!PyArg_ParseTuple(args,"Osh|lllhO:event_list_add_map_event",&argo0,&arg1,&arg2,&arg3,&arg4,&arg5,&arg6,&argo7)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event_list,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo7,(void **) &arg7,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->add_map_event(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_event_list_events_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event_list *arg0 ;
    vector<event*> *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:event_list_events_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event_list,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_vector_event__,1)) == -1) return NULL;
    arg0->events = *arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_event_list_events_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event_list *arg0 ;
    PyObject * argo0 =0 ;
    vector<event*> *result ;
    
    if(!PyArg_ParseTuple(args,"O:event_list_events_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event_list,1)) == -1) return NULL;
    result = (vector<event*> *)& (arg0->events);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_vector_event__);
    return resultobj;
}


static PyObject *_wrap_new_event_list(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event_list *result ;
    
    if(!PyArg_ParseTuple(args,":new_event_list")) return NULL;
    result = (event_list *)new event_list();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_event_list);
    return resultobj;
}


static PyObject *_wrap_event_handler_register_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Os:event_handler_register_event",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event,1)) == -1) return NULL;
    event_handler::register_event(arg0,arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_event_handler_remove_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:event_handler_remove_event",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event,1)) == -1) return NULL;
    event_handler::remove_event(arg0);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_event_handler_raise_event(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:event_handler_raise_event",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event,1)) == -1) return NULL;
    event_handler::raise_event(arg0);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_new_event_handler(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event_handler *result ;
    
    if(!PyArg_ParseTuple(args,":new_event_handler")) return NULL;
    result = (event_handler *)new event_handler();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_event_handler);
    return resultobj;
}


static PyObject *_wrap_delete_event_handler(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    event_handler *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_event_handler",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_event_handler,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyMethodDef eventcMethods[] = {
	 { "event_script_file_set", _wrap_event_script_file_set, METH_VARARGS },
	 { "event_script_file_get", _wrap_event_script_file_get, METH_VARARGS },
	 { "event_save", _wrap_event_save, METH_VARARGS },
	 { "delete_event", _wrap_delete_event, METH_VARARGS },
	 { "base_map_event_save", _wrap_base_map_event_save, METH_VARARGS },
	 { "base_map_event_submap_set", _wrap_base_map_event_submap_set, METH_VARARGS },
	 { "base_map_event_submap_get", _wrap_base_map_event_submap_get, METH_VARARGS },
	 { "base_map_event_x_set", _wrap_base_map_event_x_set, METH_VARARGS },
	 { "base_map_event_x_get", _wrap_base_map_event_x_get, METH_VARARGS },
	 { "base_map_event_y_set", _wrap_base_map_event_y_set, METH_VARARGS },
	 { "base_map_event_y_get", _wrap_base_map_event_y_get, METH_VARARGS },
	 { "base_map_event_dir_set", _wrap_base_map_event_dir_set, METH_VARARGS },
	 { "base_map_event_dir_get", _wrap_base_map_event_dir_get, METH_VARARGS },
	 { "base_map_event_map_set", _wrap_base_map_event_map_set, METH_VARARGS },
	 { "base_map_event_map_get", _wrap_base_map_event_map_get, METH_VARARGS },
	 { "base_map_event_c_set", _wrap_base_map_event_c_set, METH_VARARGS },
	 { "base_map_event_c_get", _wrap_base_map_event_c_get, METH_VARARGS },
	 { "new_base_map_event", _wrap_new_base_map_event, METH_VARARGS },
	 { "delete_base_map_event", _wrap_delete_base_map_event, METH_VARARGS },
	 { "base_map_event_script_file_set", _wrap_event_script_file_set, METH_VARARGS },
	 { "base_map_event_script_file_get", _wrap_event_script_file_get, METH_VARARGS },
	 { "new_enter_event", _wrap_new_enter_event, METH_VARARGS },
	 { "delete_enter_event", _wrap_delete_enter_event, METH_VARARGS },
	 { "enter_event_submap_set", _wrap_base_map_event_submap_set, METH_VARARGS },
	 { "enter_event_submap_get", _wrap_base_map_event_submap_get, METH_VARARGS },
	 { "enter_event_x_set", _wrap_base_map_event_x_set, METH_VARARGS },
	 { "enter_event_x_get", _wrap_base_map_event_x_get, METH_VARARGS },
	 { "enter_event_y_set", _wrap_base_map_event_y_set, METH_VARARGS },
	 { "enter_event_y_get", _wrap_base_map_event_y_get, METH_VARARGS },
	 { "enter_event_dir_set", _wrap_base_map_event_dir_set, METH_VARARGS },
	 { "enter_event_dir_get", _wrap_base_map_event_dir_get, METH_VARARGS },
	 { "enter_event_map_set", _wrap_base_map_event_map_set, METH_VARARGS },
	 { "enter_event_map_get", _wrap_base_map_event_map_get, METH_VARARGS },
	 { "enter_event_c_set", _wrap_base_map_event_c_set, METH_VARARGS },
	 { "enter_event_c_get", _wrap_base_map_event_c_get, METH_VARARGS },
	 { "enter_event_script_file_set", _wrap_event_script_file_set, METH_VARARGS },
	 { "enter_event_script_file_get", _wrap_event_script_file_get, METH_VARARGS },
	 { "new_leave_event", _wrap_new_leave_event, METH_VARARGS },
	 { "delete_leave_event", _wrap_delete_leave_event, METH_VARARGS },
	 { "leave_event_submap_set", _wrap_base_map_event_submap_set, METH_VARARGS },
	 { "leave_event_submap_get", _wrap_base_map_event_submap_get, METH_VARARGS },
	 { "leave_event_x_set", _wrap_base_map_event_x_set, METH_VARARGS },
	 { "leave_event_x_get", _wrap_base_map_event_x_get, METH_VARARGS },
	 { "leave_event_y_set", _wrap_base_map_event_y_set, METH_VARARGS },
	 { "leave_event_y_get", _wrap_base_map_event_y_get, METH_VARARGS },
	 { "leave_event_dir_set", _wrap_base_map_event_dir_set, METH_VARARGS },
	 { "leave_event_dir_get", _wrap_base_map_event_dir_get, METH_VARARGS },
	 { "leave_event_map_set", _wrap_base_map_event_map_set, METH_VARARGS },
	 { "leave_event_map_get", _wrap_base_map_event_map_get, METH_VARARGS },
	 { "leave_event_c_set", _wrap_base_map_event_c_set, METH_VARARGS },
	 { "leave_event_c_get", _wrap_base_map_event_c_get, METH_VARARGS },
	 { "leave_event_script_file_set", _wrap_event_script_file_set, METH_VARARGS },
	 { "leave_event_script_file_get", _wrap_event_script_file_get, METH_VARARGS },
	 { "new_time_event", _wrap_new_time_event, METH_VARARGS },
	 { "time_event_save", _wrap_time_event_save, METH_VARARGS },
	 { "time_event_minute_set", _wrap_time_event_minute_set, METH_VARARGS },
	 { "time_event_minute_get", _wrap_time_event_minute_get, METH_VARARGS },
	 { "time_event_m_step_set", _wrap_time_event_m_step_set, METH_VARARGS },
	 { "time_event_m_step_get", _wrap_time_event_m_step_get, METH_VARARGS },
	 { "time_event_hour_set", _wrap_time_event_hour_set, METH_VARARGS },
	 { "time_event_hour_get", _wrap_time_event_hour_get, METH_VARARGS },
	 { "time_event_h_step_set", _wrap_time_event_h_step_set, METH_VARARGS },
	 { "time_event_h_step_get", _wrap_time_event_h_step_get, METH_VARARGS },
	 { "time_event_day_set", _wrap_time_event_day_set, METH_VARARGS },
	 { "time_event_day_get", _wrap_time_event_day_get, METH_VARARGS },
	 { "time_event_d_step_set", _wrap_time_event_d_step_set, METH_VARARGS },
	 { "time_event_d_step_get", _wrap_time_event_d_step_get, METH_VARARGS },
	 { "time_event_time_set", _wrap_time_event_time_set, METH_VARARGS },
	 { "time_event_time_get", _wrap_time_event_time_get, METH_VARARGS },
	 { "delete_time_event", _wrap_delete_time_event, METH_VARARGS },
	 { "time_event_script_file_set", _wrap_event_script_file_set, METH_VARARGS },
	 { "time_event_script_file_get", _wrap_event_script_file_get, METH_VARARGS },
	 { "delete_event_list", _wrap_delete_event_list, METH_VARARGS },
	 { "event_list_add_event", _wrap_event_list_add_event, METH_VARARGS },
	 { "event_list_add_map_event", _wrap_event_list_add_map_event, METH_VARARGS },
	 { "event_list_events_set", _wrap_event_list_events_set, METH_VARARGS },
	 { "event_list_events_get", _wrap_event_list_events_get, METH_VARARGS },
	 { "new_event_list", _wrap_new_event_list, METH_VARARGS },
	 { "event_handler_register_event", _wrap_event_handler_register_event, METH_VARARGS },
	 { "event_handler_remove_event", _wrap_event_handler_remove_event, METH_VARARGS },
	 { "event_handler_raise_event", _wrap_event_handler_raise_event, METH_VARARGS },
	 { "new_event_handler", _wrap_new_event_handler, METH_VARARGS },
	 { "delete_event_handler", _wrap_delete_event_handler, METH_VARARGS },
	 { NULL, NULL }
};

#ifdef __cplusplus
}
#endif

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static void *_p_leave_eventTo_p_event(void *x) {
    return (void *)((event *) ((leave_event *) x));
}
static void *_p_time_eventTo_p_event(void *x) {
    return (void *)((event *) ((time_event *) x));
}
static void *_p_base_map_eventTo_p_event(void *x) {
    return (void *)((event *) ((base_map_event *) x));
}
static void *_p_enter_eventTo_p_event(void *x) {
    return (void *)((event *) ((enter_event *) x));
}
static void *_p_leave_eventTo_p_base_map_event(void *x) {
    return (void *)((base_map_event *) ((leave_event *) x));
}
static void *_p_enter_eventTo_p_base_map_event(void *x) {
    return (void *)((base_map_event *) ((enter_event *) x));
}
static swig_type_info _swigt__p_event_handler[] = {{"_p_event_handler", 0, "event_handler *"},{"_p_event_handler"},{0}};
static swig_type_info _swigt__p_leave_event[] = {{"_p_leave_event", 0, "leave_event *"},{"_p_leave_event"},{0}};
static swig_type_info _swigt__p_time_event[] = {{"_p_time_event", 0, "time_event *"},{"_p_time_event"},{0}};
static swig_type_info _swigt__p_event[] = {{"_p_event", 0, "event *"},{"_p_time_event", _p_time_eventTo_p_event},{"_p_leave_event", _p_leave_eventTo_p_event},{"_p_event"},{"_p_base_map_event", _p_base_map_eventTo_p_event},{"_p_enter_event", _p_enter_eventTo_p_event},{0}};
static swig_type_info _swigt__p_base_map_event[] = {{"_p_base_map_event", 0, "base_map_event *"},{"_p_leave_event", _p_leave_eventTo_p_base_map_event},{"_p_base_map_event"},{"_p_enter_event", _p_enter_eventTo_p_base_map_event},{0}};
static swig_type_info _swigt__p_enter_event[] = {{"_p_enter_event", 0, "enter_event *"},{"_p_enter_event"},{0}};
static swig_type_info _swigt__p_vector_event__[] = {{"_p_vector_event__", 0, "vector<event*> *"},{"_p_vector_event__"},{0}};
static swig_type_info _swigt__p_gzFile[] = {{"_p_gzFile", 0, "gzFile *"},{"_p_gzFile"},{0}};
static swig_type_info _swigt__p_mapcharacter[] = {{"_p_mapcharacter", 0, "mapcharacter *"},{"_p_mapcharacter"},{0}};
static swig_type_info _swigt__p_event_list[] = {{"_p_event_list", 0, "event_list *"},{"_p_event_list"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_event_handler, 
_swigt__p_leave_event, 
_swigt__p_time_event, 
_swigt__p_event, 
_swigt__p_base_map_event, 
_swigt__p_enter_event, 
_swigt__p_vector_event__, 
_swigt__p_gzFile, 
_swigt__p_mapcharacter, 
_swigt__p_event_list, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
    { SWIG_PY_INT,     "ENTER_EVENT", (long) ENTER_EVENT, 0, 0, 0},
    { SWIG_PY_INT,     "LEAVE_EVENT", (long) LEAVE_EVENT, 0, 0, 0},
    { SWIG_PY_INT,     "TIME_EVENT", (long) TIME_EVENT, 0, 0, 0},
    { SWIG_PY_INT,     "MAX_EVENT", (long) MAX_EVENT, 0, 0, 0},
{0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initeventc(void) {
    PyObject *m, *d;
    int i;
    SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule("eventc", eventcMethods);
    d = PyModule_GetDict(m);
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    SWIG_InstallConstants(d,swig_const_table);
}

