/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3u-20001216-1131 (Alpha 5)
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct swig_type_info {
  char  *name;                 
  void *(*converter)(void *);
  char  *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(void *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

#endif

#ifdef __cplusplus
}
#endif



/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(void)              SWIG_MakePtr(char *c, void *, swig_type_info *);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  "swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}
/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  unsigned long p;
  register int d;
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj || (obj == Py_None)) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  /* Extract hex value from pointer */
  while ((d = *c)) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*)p);
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Take a pointer and convert it to a string */
SWIGRUNTIME(void) 
SWIG_MakePtr(char *c, void *ptr, swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[32], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type) {
  char result[512];
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, type->name, NULL);
#else
  SWIG_MakePtr(result,ptr,type);
  robj = PyString_FromString(result);
#endif
  return robj;
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype);
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif



/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_landmap swig_types[0] 
#define  SWIGTYPE_p_drawing_area swig_types[1] 
#define  SWIGTYPE_p_mapcharacter swig_types[2] 
#define  SWIGTYPE_p_gzFile swig_types[3] 
#define  SWIGTYPE_p_mapview swig_types[4] 
static swig_type_info *swig_types[6];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= landmapc.so
  ------------------------------------------------*/
#define SWIG_init    initlandmapc

#define SWIG_name    "landmapc"


#include "landmap.h"

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_mapcharacter_init(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_init",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->init();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_clear(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_clear",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->clear();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_new_mapcharacter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *result ;
    
    if(!PyArg_ParseTuple(args,":new_mapcharacter")) return NULL;
    result = (mapcharacter *)new mapcharacter();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_mapcharacter);
    return resultobj;
}


static PyObject *_wrap_delete_mapcharacter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_mapcharacter",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    gzFile *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"OO:mapcharacter_get",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_gzFile,1)) == -1) return NULL;
    result = (signed char )arg0->get(*arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_load(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"Os:mapcharacter_load",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (signed char )arg0->load((char const *)arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_get_posx(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_get_posx",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (unsigned short )arg0->get_posx();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_get_posy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_get_posy",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (unsigned short )arg0->get_posy();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_get_offx(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_get_offx",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (signed char )arg0->get_offx();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_get_offy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_get_offy",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (signed char )arg0->get_offy();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_set_on_map(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    landmap *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:mapcharacter_set_on_map",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    arg0->set_on_map(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_remove_from_map(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_remove_from_map",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->remove_from_map();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_set_pos(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    unsigned short arg1 ;
    unsigned short arg2 ;
    unsigned short arg3 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ohhh:mapcharacter_set_pos",&argo0,&arg1,&arg2,&arg3)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->set_pos(arg1,arg2,arg3);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_set_offset(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    signed char arg1 ;
    signed char arg2 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Obb:mapcharacter_set_offset",&argo0,&arg1,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->set_offset(arg1,arg2);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_move(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_move",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (unsigned short )arg0->move();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_set_schedule(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Os:mapcharacter_set_schedule",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->set_schedule(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_is_schedule_activated(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_is_schedule_activated",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (bool )arg0->is_schedule_activated();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_set_schedule_active(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:mapcharacter_set_schedule_active",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_schedule_active(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_update_move(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_update_move",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->update_move();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_update(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_update",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->update();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_draw(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    mapview *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:mapcharacter_draw",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_mapview,1)) == -1) return NULL;
    arg0->draw(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_can_go_north(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_can_go_north",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (bool )arg0->can_go_north();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_can_go_south(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_can_go_south",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (bool )arg0->can_go_south();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_can_go_east(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_can_go_east",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (bool )arg0->can_go_east();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_can_go_west(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_can_go_west",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    result = (bool )arg0->can_go_west();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_mapcharacter_stand_north(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_stand_north",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->stand_north();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_stand_south(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_stand_south",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->stand_south();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_stand_east(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_stand_east",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->stand_east();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_stand_west(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_stand_west",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->stand_west();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_go_north(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_go_north",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->go_north();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_go_south(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_go_south",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->go_south();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_go_east(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_go_east",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->go_east();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_mapcharacter_go_west(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    mapcharacter *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:mapcharacter_go_west",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->go_west();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_landmap_nbr_of_patterns_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    unsigned short arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Oh:landmap_nbr_of_patterns_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    arg0->nbr_of_patterns = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_landmap_nbr_of_patterns_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:landmap_nbr_of_patterns_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (unsigned short ) (arg0->nbr_of_patterns);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_landmap_nbr_of_submaps_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    unsigned short arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Oh:landmap_nbr_of_submaps_set",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    arg0->nbr_of_submaps = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_landmap_nbr_of_submaps_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:landmap_nbr_of_submaps_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (unsigned short ) (arg0->nbr_of_submaps);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_new_landmap(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *result ;
    
    if(!PyArg_ParseTuple(args,":new_landmap")) return NULL;
    result = (landmap *)new landmap();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_landmap);
    return resultobj;
}


static PyObject *_wrap_landmap_clear(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:landmap_clear",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    arg0->clear();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_delete_landmap(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_landmap",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_landmap_get_nbr_of_patterns(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:landmap_get_nbr_of_patterns",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (unsigned short )arg0->get_nbr_of_patterns();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_landmap_get_nbr_of_submaps(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:landmap_get_nbr_of_submaps",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (unsigned short )arg0->get_nbr_of_submaps();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_landmap_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    gzFile *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"OO:landmap_get",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_gzFile,1)) == -1) return NULL;
    result = (signed char )arg0->get(*arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_landmap_load(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"Os:landmap_load",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (signed char )arg0->load((char const *)arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_landmap_put_mapchar(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    mapcharacter *arg1 ;
    unsigned short arg2 ;
    unsigned short arg3 ;
    unsigned short arg4 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OOhhh:landmap_put_mapchar",&argo0,&argo1,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->put_mapchar(arg1,arg2,arg3,arg4);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_landmap_remove_mapchar(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    mapcharacter *arg1 ;
    unsigned short arg2 ;
    unsigned short arg3 ;
    unsigned short arg4 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OOhhh:landmap_remove_mapchar",&argo0,&argo1,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->remove_mapchar(arg1,arg2,arg3,arg4);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_landmap_add_mapcharacter(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    mapcharacter *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:landmap_add_mapcharacter",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_mapcharacter,1)) == -1) return NULL;
    arg0->add_mapcharacter(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_landmap_get_mapchar(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    unsigned short arg1 ;
    PyObject * argo0 =0 ;
    mapcharacter *result ;
    
    if(!PyArg_ParseTuple(args,"Oh:landmap_get_mapchar",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (mapcharacter *)arg0->get_mapchar(arg1);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_mapcharacter);
    return resultobj;
}


static PyObject *_wrap_landmap_add_submap(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    PyObject * argo0 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"O:landmap_add_submap",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (signed char )arg0->add_submap();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_landmap_remove_submap(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    unsigned short arg1 ;
    PyObject * argo0 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"Oh:landmap_remove_submap",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (signed char )arg0->remove_submap(arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_landmap_set_square_pattern(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    unsigned short arg1 ;
    unsigned short arg2 ;
    unsigned short arg3 ;
    unsigned short arg4 ;
    PyObject * argo0 =0 ;
    signed char result ;
    
    if(!PyArg_ParseTuple(args,"Ohhhh:landmap_set_square_pattern",&argo0,&arg1,&arg2,&arg3,&arg4)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    result = (signed char )arg0->set_square_pattern(arg1,arg2,arg3,arg4);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_landmap_update(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:landmap_update",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    arg0->update();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_landmap_draw_square(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    landmap *arg0 ;
    unsigned short arg1 ;
    unsigned short arg2 ;
    unsigned short arg3 ;
    unsigned short arg4 ;
    unsigned short arg5 ;
    drawing_area *arg6 = NULL ;
    PyObject * argo0 =0 ;
    PyObject * argo6 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ohhhhh|O:landmap_draw_square",&argo0,&arg1,&arg2,&arg3,&arg4,&arg5,&argo6)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_landmap,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo6,(void **) &arg6,SWIGTYPE_p_drawing_area,1)) == -1) return NULL;
    arg0->draw_square(arg1,arg2,arg3,arg4,arg5,arg6);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyMethodDef landmapcMethods[] = {
	 { "mapcharacter_init", _wrap_mapcharacter_init, METH_VARARGS },
	 { "mapcharacter_clear", _wrap_mapcharacter_clear, METH_VARARGS },
	 { "new_mapcharacter", _wrap_new_mapcharacter, METH_VARARGS },
	 { "delete_mapcharacter", _wrap_delete_mapcharacter, METH_VARARGS },
	 { "mapcharacter_get", _wrap_mapcharacter_get, METH_VARARGS },
	 { "mapcharacter_load", _wrap_mapcharacter_load, METH_VARARGS },
	 { "mapcharacter_get_posx", _wrap_mapcharacter_get_posx, METH_VARARGS },
	 { "mapcharacter_get_posy", _wrap_mapcharacter_get_posy, METH_VARARGS },
	 { "mapcharacter_get_offx", _wrap_mapcharacter_get_offx, METH_VARARGS },
	 { "mapcharacter_get_offy", _wrap_mapcharacter_get_offy, METH_VARARGS },
	 { "mapcharacter_set_on_map", _wrap_mapcharacter_set_on_map, METH_VARARGS },
	 { "mapcharacter_remove_from_map", _wrap_mapcharacter_remove_from_map, METH_VARARGS },
	 { "mapcharacter_set_pos", _wrap_mapcharacter_set_pos, METH_VARARGS },
	 { "mapcharacter_set_offset", _wrap_mapcharacter_set_offset, METH_VARARGS },
	 { "mapcharacter_move", _wrap_mapcharacter_move, METH_VARARGS },
	 { "mapcharacter_set_schedule", _wrap_mapcharacter_set_schedule, METH_VARARGS },
	 { "mapcharacter_is_schedule_activated", _wrap_mapcharacter_is_schedule_activated, METH_VARARGS },
	 { "mapcharacter_set_schedule_active", _wrap_mapcharacter_set_schedule_active, METH_VARARGS },
	 { "mapcharacter_update_move", _wrap_mapcharacter_update_move, METH_VARARGS },
	 { "mapcharacter_update", _wrap_mapcharacter_update, METH_VARARGS },
	 { "mapcharacter_draw", _wrap_mapcharacter_draw, METH_VARARGS },
	 { "mapcharacter_can_go_north", _wrap_mapcharacter_can_go_north, METH_VARARGS },
	 { "mapcharacter_can_go_south", _wrap_mapcharacter_can_go_south, METH_VARARGS },
	 { "mapcharacter_can_go_east", _wrap_mapcharacter_can_go_east, METH_VARARGS },
	 { "mapcharacter_can_go_west", _wrap_mapcharacter_can_go_west, METH_VARARGS },
	 { "mapcharacter_stand_north", _wrap_mapcharacter_stand_north, METH_VARARGS },
	 { "mapcharacter_stand_south", _wrap_mapcharacter_stand_south, METH_VARARGS },
	 { "mapcharacter_stand_east", _wrap_mapcharacter_stand_east, METH_VARARGS },
	 { "mapcharacter_stand_west", _wrap_mapcharacter_stand_west, METH_VARARGS },
	 { "mapcharacter_go_north", _wrap_mapcharacter_go_north, METH_VARARGS },
	 { "mapcharacter_go_south", _wrap_mapcharacter_go_south, METH_VARARGS },
	 { "mapcharacter_go_east", _wrap_mapcharacter_go_east, METH_VARARGS },
	 { "mapcharacter_go_west", _wrap_mapcharacter_go_west, METH_VARARGS },
	 { "landmap_nbr_of_patterns_set", _wrap_landmap_nbr_of_patterns_set, METH_VARARGS },
	 { "landmap_nbr_of_patterns_get", _wrap_landmap_nbr_of_patterns_get, METH_VARARGS },
	 { "landmap_nbr_of_submaps_set", _wrap_landmap_nbr_of_submaps_set, METH_VARARGS },
	 { "landmap_nbr_of_submaps_get", _wrap_landmap_nbr_of_submaps_get, METH_VARARGS },
	 { "new_landmap", _wrap_new_landmap, METH_VARARGS },
	 { "landmap_clear", _wrap_landmap_clear, METH_VARARGS },
	 { "delete_landmap", _wrap_delete_landmap, METH_VARARGS },
	 { "landmap_get_nbr_of_patterns", _wrap_landmap_get_nbr_of_patterns, METH_VARARGS },
	 { "landmap_get_nbr_of_submaps", _wrap_landmap_get_nbr_of_submaps, METH_VARARGS },
	 { "landmap_get", _wrap_landmap_get, METH_VARARGS },
	 { "landmap_load", _wrap_landmap_load, METH_VARARGS },
	 { "landmap_put_mapchar", _wrap_landmap_put_mapchar, METH_VARARGS },
	 { "landmap_remove_mapchar", _wrap_landmap_remove_mapchar, METH_VARARGS },
	 { "landmap_add_mapcharacter", _wrap_landmap_add_mapcharacter, METH_VARARGS },
	 { "landmap_get_mapchar", _wrap_landmap_get_mapchar, METH_VARARGS },
	 { "landmap_add_submap", _wrap_landmap_add_submap, METH_VARARGS },
	 { "landmap_remove_submap", _wrap_landmap_remove_submap, METH_VARARGS },
	 { "landmap_set_square_pattern", _wrap_landmap_set_square_pattern, METH_VARARGS },
	 { "landmap_update", _wrap_landmap_update, METH_VARARGS },
	 { "landmap_draw_square", _wrap_landmap_draw_square, METH_VARARGS },
	 { NULL, NULL }
};

#ifdef __cplusplus
}
#endif

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_landmap[] = {{"_p_landmap", 0, "landmap *"},{"_p_landmap"},{0}};
static swig_type_info _swigt__p_drawing_area[] = {{"_p_drawing_area", 0, "drawing_area *"},{"_p_drawing_area"},{0}};
static swig_type_info _swigt__p_mapcharacter[] = {{"_p_mapcharacter", 0, "mapcharacter *"},{"_p_mapcharacter"},{0}};
static swig_type_info _swigt__p_gzFile[] = {{"_p_gzFile", 0, "gzFile *"},{"_p_gzFile"},{0}};
static swig_type_info _swigt__p_mapview[] = {{"_p_mapview", 0, "mapview *"},{"_p_mapview"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_landmap, 
_swigt__p_drawing_area, 
_swigt__p_mapcharacter, 
_swigt__p_gzFile, 
_swigt__p_mapview, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
    { SWIG_PY_INT,     "STAND_NORTH", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "STAND_SOUTH", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "STAND_WEST", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "STAND_EAST", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "WALK_NORTH", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "WALK_SOUTH", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "WALK_WEST", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "WALK_EAST", (long) 7, 0, 0, 0},
    { SWIG_PY_INT,     "NBR_MOVES", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "NO_MOVE", (long) 65535, 0, 0, 0},
{0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initlandmapc(void) {
    PyObject *m, *d;
    int i;
    SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule("landmapc", landmapcMethods);
    d = PyModule_GetDict(m);
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    SWIG_InstallConstants(d,swig_const_table);
}

