/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3u-20010315-0010 (Alpha 5)
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct swig_type_info {
  char  *name;                 
  void *(*converter)(void *);
  char  *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(void *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

#endif

#ifdef __cplusplus
}
#endif



/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(void)              SWIG_MakePtr(char *c, void *, swig_type_info *);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  "swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}
/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  unsigned long p;
  register int d;
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj || (obj == Py_None)) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  /* Extract hex value from pointer */
  while ((d = *c)) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*)p);
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Take a pointer and convert it to a string */
SWIGRUNTIME(void) 
SWIG_MakePtr(char *c, void *ptr, swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[32], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type) {
  char result[512];
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, type->name, NULL);
#else
  SWIG_MakePtr(result,ptr,type);
  robj = PyString_FromString(result);
#endif
  return robj;
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype);
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif



/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_win_font swig_types[0] 
#define  SWIGTYPE_p_win_base swig_types[1] 
#define  SWIGTYPE_p_drawing_area swig_types[2] 
#define  SWIGTYPE_p_win_theme swig_types[3] 
#define  SWIGTYPE_p_win_label swig_types[4] 
#define  SWIGTYPE_p_Functor0wRet_bool_ swig_types[5] 
#define  SWIGTYPE_p_short swig_types[6] 
#define  SWIGTYPE_p_Functor0 swig_types[7] 
static swig_type_info *swig_types[9];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= win_labelc.so
  ------------------------------------------------*/
#define SWIG_init    initwin_labelc

#define SWIG_name    "win_labelc"


#include "types.h"
#include "image.h"
#include "win_types.h"
#include "win_font.h"
#include "win_theme.h"
#include "win_border.h"
#include "win_background.h"
#include "win_base.h"
#include "win_label.h"

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_new_win_base(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    short arg0 ;
    short arg1 ;
    unsigned short arg2 ;
    unsigned short arg3 ;
    win_theme *arg4 ;
    PyObject * argo4 =0 ;
    win_base *result ;
    
    if(!PyArg_ParseTuple(args,"hhhhO:new_win_base",&arg0,&arg1,&arg2,&arg3,&argo4)) return NULL;
    if ((SWIG_ConvertPtr(argo4,(void **) &arg4,SWIGTYPE_p_win_theme,1)) == -1) return NULL;
    result = (win_base *)new win_base(arg0,arg1,arg2,arg3,arg4);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_win_base);
    return resultobj;
}


static PyObject *_wrap_delete_win_base(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_win_base",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_x(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    short result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_x",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (short )arg0->x();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_y(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    short result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_y",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (short )arg0->y();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_length(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_length",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (unsigned short )arg0->length();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_height(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_height",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (unsigned short )arg0->height();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_padx(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    short *result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_padx",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    short &_result_ref = arg0->padx();
    result = (short *) &_result_ref;
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_short);
    return resultobj;
}


static PyObject *_wrap_win_base_pady(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    short *result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_pady",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    short &_result_ref = arg0->pady();
    result = (short *) &_result_ref;
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_short);
    return resultobj;
}


static PyObject *_wrap_win_base_realx(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    short result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_realx",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (short )arg0->realx();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_realy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    short result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_realy",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (short )arg0->realy();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_move(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    short arg1 ;
    short arg2 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ohh:win_base_move",&argo0,&arg1,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg0->move(arg1,arg2);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_resize(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    unsigned short arg1 ;
    unsigned short arg2 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ohh:win_base_resize",&argo0,&arg1,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg0->resize(arg1,arg2);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_set_border_size(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    unsigned char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:win_base_set_border_size",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg0->set_border_size(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_set_visible(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:win_base_set_visible",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_visible(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_is_visible(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_is_visible",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (bool )arg0->is_visible();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_set_background_visible(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:win_base_set_background_visible",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_background_visible(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_is_background_visible(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_is_background_visible",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (bool )arg0->is_background_visible();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_set_border_visible(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:win_base_set_border_visible",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_border_visible(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_is_border_visible(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_is_border_visible",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (bool )arg0->is_border_visible();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_set_signal_connect(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    Functor0 *arg1 ;
    unsigned char arg2 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OOb:win_base_set_signal_connect",&argo0,&argo1,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_Functor0,1)) == -1) return NULL;
    arg0->set_signal_connect((Functor0 const &)*arg1,arg2);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_set_callback_destroy(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    Functor0wRet<bool> *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:win_base_set_callback_destroy",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_Functor0wRet_bool_,1)) == -1) return NULL;
    arg0->set_callback_destroy((Functor0wRet<bool> const &)*arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_set_activated(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:win_base_set_activated",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_activated(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_is_activated(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_is_activated",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (bool )arg0->is_activated();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_is_in_select(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_is_in_select",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (bool )arg0->is_in_select();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_is_select(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_is_select",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (bool )arg0->is_select();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_set_draw_brightness(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:win_base_set_draw_brightness",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_draw_brightness(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_set_level_brightness(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    unsigned short arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Oh:win_base_set_level_brightness",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg0->set_level_brightness(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_set_level_trans_background(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    unsigned short arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Oh:win_base_set_level_trans_background",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg0->set_level_trans_background(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_set_theme(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    win_theme *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:win_base_set_theme",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_win_theme,1)) == -1) return NULL;
    arg0->set_theme(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_get_drawing_area(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    drawing_area *result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_get_drawing_area",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (drawing_area *)arg0->get_drawing_area();
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_drawing_area);
    return resultobj;
}


static PyObject *_wrap_win_base_update(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_update",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (bool )arg0->update();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_base_update_real_position(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_update_real_position",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    arg0->update_real_position();
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_base_draw(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_base *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_base_draw",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_base,1)) == -1) return NULL;
    result = (bool )arg0->draw();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_new_win_label(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    short arg0 ;
    short arg1 ;
    unsigned short arg2 ;
    unsigned short arg3 ;
    win_theme *arg4 ;
    win_font *arg5 ;
    PyObject * argo4 =0 ;
    PyObject * argo5 =0 ;
    win_label *result ;
    
    if(!PyArg_ParseTuple(args,"hhhhOO:new_win_label",&arg0,&arg1,&arg2,&arg3,&argo4,&argo5)) return NULL;
    if ((SWIG_ConvertPtr(argo4,(void **) &arg4,SWIGTYPE_p_win_theme,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo5,(void **) &arg5,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    result = (win_label *)new win_label(arg0,arg1,arg2,arg3,arg4,arg5);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_win_label);
    return resultobj;
}


static PyObject *_wrap_win_label_draw(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_label_draw",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    result = (bool )arg0->draw();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_label_set_text(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Os:win_label_set_text",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    arg0->set_text((char const *)arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_label_add_text(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Os:win_label_add_text",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    arg0->add_text((char const *)arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_label_is_auto_size(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_label_is_auto_size",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    result = (bool )arg0->is_auto_size();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_label_is_auto_height(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_label_is_auto_height",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    result = (bool )arg0->is_auto_height();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_label_set_auto_size(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:win_label_set_auto_size",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_auto_size(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_label_set_auto_height(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:win_label_set_auto_height",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_auto_height(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_label_resize(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    unsigned short arg1 ;
    unsigned short arg2 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ohh:win_label_resize",&argo0,&arg1,&arg2)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    arg0->resize(arg1,arg2);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_label_update(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_label_update",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    result = (bool )arg0->update();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_label_set_cursor_blinking(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    bool arg1 ;
    PyObject * argo0 =0 ;
    int tempbool1 ;
    
    if(!PyArg_ParseTuple(args,"Oi:win_label_set_cursor_blinking",&argo0,&tempbool1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    arg1 = (bool ) tempbool1;
    arg0->set_cursor_blinking(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_label_is_cursor_blinking(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"O:win_label_is_cursor_blinking",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    result = (bool )arg0->is_cursor_blinking();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_label_set_cursor_blinking_speed(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    unsigned char arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Ob:win_label_set_cursor_blinking_speed",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    arg0->set_cursor_blinking_speed(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_label_get_text(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    PyObject * argo0 =0 ;
    char *result ;
    
    if(!PyArg_ParseTuple(args,"O:win_label_get_text",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    result = (char *)arg0->get_text();
    resultobj = PyString_FromString(result);
    return resultobj;
}


static PyObject *_wrap_delete_win_label(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_label *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_win_label",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_label,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyMethodDef win_labelcMethods[] = {
	 { "new_win_base", _wrap_new_win_base, METH_VARARGS },
	 { "delete_win_base", _wrap_delete_win_base, METH_VARARGS },
	 { "win_base_x", _wrap_win_base_x, METH_VARARGS },
	 { "win_base_y", _wrap_win_base_y, METH_VARARGS },
	 { "win_base_length", _wrap_win_base_length, METH_VARARGS },
	 { "win_base_height", _wrap_win_base_height, METH_VARARGS },
	 { "win_base_padx", _wrap_win_base_padx, METH_VARARGS },
	 { "win_base_pady", _wrap_win_base_pady, METH_VARARGS },
	 { "win_base_realx", _wrap_win_base_realx, METH_VARARGS },
	 { "win_base_realy", _wrap_win_base_realy, METH_VARARGS },
	 { "win_base_move", _wrap_win_base_move, METH_VARARGS },
	 { "win_base_resize", _wrap_win_base_resize, METH_VARARGS },
	 { "win_base_set_border_size", _wrap_win_base_set_border_size, METH_VARARGS },
	 { "win_base_set_visible", _wrap_win_base_set_visible, METH_VARARGS },
	 { "win_base_is_visible", _wrap_win_base_is_visible, METH_VARARGS },
	 { "win_base_set_background_visible", _wrap_win_base_set_background_visible, METH_VARARGS },
	 { "win_base_is_background_visible", _wrap_win_base_is_background_visible, METH_VARARGS },
	 { "win_base_set_border_visible", _wrap_win_base_set_border_visible, METH_VARARGS },
	 { "win_base_is_border_visible", _wrap_win_base_is_border_visible, METH_VARARGS },
	 { "win_base_set_signal_connect", _wrap_win_base_set_signal_connect, METH_VARARGS },
	 { "win_base_set_callback_destroy", _wrap_win_base_set_callback_destroy, METH_VARARGS },
	 { "win_base_set_activated", _wrap_win_base_set_activated, METH_VARARGS },
	 { "win_base_is_activated", _wrap_win_base_is_activated, METH_VARARGS },
	 { "win_base_is_in_select", _wrap_win_base_is_in_select, METH_VARARGS },
	 { "win_base_is_select", _wrap_win_base_is_select, METH_VARARGS },
	 { "win_base_set_draw_brightness", _wrap_win_base_set_draw_brightness, METH_VARARGS },
	 { "win_base_set_level_brightness", _wrap_win_base_set_level_brightness, METH_VARARGS },
	 { "win_base_set_level_trans_background", _wrap_win_base_set_level_trans_background, METH_VARARGS },
	 { "win_base_set_theme", _wrap_win_base_set_theme, METH_VARARGS },
	 { "win_base_get_drawing_area", _wrap_win_base_get_drawing_area, METH_VARARGS },
	 { "win_base_update", _wrap_win_base_update, METH_VARARGS },
	 { "win_base_update_real_position", _wrap_win_base_update_real_position, METH_VARARGS },
	 { "win_base_draw", _wrap_win_base_draw, METH_VARARGS },
	 { "new_win_label", _wrap_new_win_label, METH_VARARGS },
	 { "win_label_draw", _wrap_win_label_draw, METH_VARARGS },
	 { "win_label_set_text", _wrap_win_label_set_text, METH_VARARGS },
	 { "win_label_add_text", _wrap_win_label_add_text, METH_VARARGS },
	 { "win_label_is_auto_size", _wrap_win_label_is_auto_size, METH_VARARGS },
	 { "win_label_is_auto_height", _wrap_win_label_is_auto_height, METH_VARARGS },
	 { "win_label_set_auto_size", _wrap_win_label_set_auto_size, METH_VARARGS },
	 { "win_label_set_auto_height", _wrap_win_label_set_auto_height, METH_VARARGS },
	 { "win_label_resize", _wrap_win_label_resize, METH_VARARGS },
	 { "win_label_update", _wrap_win_label_update, METH_VARARGS },
	 { "win_label_set_cursor_blinking", _wrap_win_label_set_cursor_blinking, METH_VARARGS },
	 { "win_label_is_cursor_blinking", _wrap_win_label_is_cursor_blinking, METH_VARARGS },
	 { "win_label_set_cursor_blinking_speed", _wrap_win_label_set_cursor_blinking_speed, METH_VARARGS },
	 { "win_label_get_text", _wrap_win_label_get_text, METH_VARARGS },
	 { "delete_win_label", _wrap_delete_win_label, METH_VARARGS },
	 { NULL, NULL }
};

#ifdef __cplusplus
}
#endif

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static void *_p_win_labelTo_p_win_base(void *x) {
    return (void *)((win_base *) ((win_label *) x));
}
static swig_type_info _swigt__p_win_font[] = {{"_p_win_font", 0, "win_font *"},{"_p_win_font"},{0}};
static swig_type_info _swigt__p_win_base[] = {{"_p_win_base", 0, "win_base *"},{"_p_win_base"},{"_p_win_label", _p_win_labelTo_p_win_base},{0}};
static swig_type_info _swigt__p_drawing_area[] = {{"_p_drawing_area", 0, "drawing_area *"},{"_p_drawing_area"},{0}};
static swig_type_info _swigt__p_win_theme[] = {{"_p_win_theme", 0, "win_theme *"},{"_p_win_theme"},{0}};
static swig_type_info _swigt__p_win_label[] = {{"_p_win_label", 0, "win_label *"},{"_p_win_label"},{0}};
static swig_type_info _swigt__p_Functor0wRet_bool_[] = {{"_p_Functor0wRet_bool_", 0, "Functor0wRet<bool> *"},{"_p_Functor0wRet_bool_"},{0}};
static swig_type_info _swigt__p_short[] = {{"_p_short", 0, "short *"},{"_p_short"},{0}};
static swig_type_info _swigt__p_Functor0[] = {{"_p_Functor0", 0, "Functor0 *"},{"_p_Functor0"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_win_font, 
_swigt__p_win_base, 
_swigt__p_drawing_area, 
_swigt__p_win_theme, 
_swigt__p_win_label, 
_swigt__p_Functor0wRet_bool_, 
_swigt__p_short, 
_swigt__p_Functor0, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
    { SWIG_PY_INT,     "WIN_NB_TABLE_CHAR", (long) 255, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_TEXT_MAX_LENGTH", (long) 5000, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_FONT_HEIGHT", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_FONT_LENGHT", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SPACE_LENGHT", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_JUSTIFY_LEFT", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_JUSTIFY_RIGHT", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_JUSTIFY_CENTER", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_JUSTIFY_NO", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_LAYOUT_NO", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_LAYOUT_LIST", (long) 1, 0, 0, 0},
    { SWIG_PY_STRING, "WIN_DIRECTORY", 0, 0, (void *) "gfxtree/window/", 0 }, 
    { SWIG_PY_STRING, "WIN_FONT_DIRECTORY", 0, 0, (void *) "font/", 0 }, 
    { SWIG_PY_STRING, "WIN_BORDER_DIRECTORY", 0, 0, (void *) "border/", 0 }, 
    { SWIG_PY_STRING, "WIN_BACKGROUND_DIRECTORY", 0, 0, (void *) "background/", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_DIRECTORY", 0, 0, (void *) "scrollbar/", 0 }, 
    { SWIG_PY_STRING, "WIN_CURSOR_DIRECTORY", 0, 0, (void *) "cursor/", 0 }, 
    { SWIG_PY_STRING, "WIN_FONT_FILE_IDX", 0, 0, (void *) "font.idx", 0 }, 
    { SWIG_PY_STRING, "WIN_FONT_FILE_PIC", 0, 0, (void *) "font.pnm", 0 }, 
    { SWIG_PY_INT,     "WIN_CURSOR_BLINKING", (long) 75, 0, 0, 0},
    { SWIG_PY_STRING, "WIN_V_BORDER_TEMPLATE_FILE", 0, 0, (void *) "v_border.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_H_BORDER_TEMPLATE_FILE", 0, 0, (void *) "h_border.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CORNER_TOP_LEFT_FILE", 0, 0, (void *) "corner_top_left.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CORNER_TOP_RIGHT_FILE", 0, 0, (void *) "corner_top_right.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CORNER_BOTTOM_LEFT_FILE", 0, 0, (void *) "corner_bottom_left.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CORNER_BOTTOM_RIGHT_FILE", 0, 0, (void *) "corner_bottom_right.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_BACKGROUND_FILE", 0, 0, (void *) "background.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BAR_TOP", 0, 0, (void *) "scroll_bar_top.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BAR_MID", 0, 0, (void *) "scroll_bar_mid.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BAR_BOT", 0, 0, (void *) "scroll_bar_bot.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BAR_FLEX", 0, 0, (void *) "scroll_bar_flex.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BACK_TOP", 0, 0, (void *) "scroll_back_top.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BACK_MID", 0, 0, (void *) "scroll_back_mid.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BACK_BOT", 0, 0, (void *) "scroll_back_bot.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CURSOR_FILE", 0, 0, (void *) "cursor.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_BORDER_NORMAL_SIZE", 0, 0, (void *) "normal/", 0 }, 
    { SWIG_PY_STRING, "WIN_BORDER_MINI_SIZE", 0, 0, (void *) "mini/", 0 }, 
    { SWIG_PY_STRING, "WIN_THEME_ORIGINAL", 0, 0, (void *) "original/", 0 }, 
    { SWIG_PY_STRING, "WIN_THEME_ELFE", 0, 0, (void *) "silverleaf/", 0 }, 
    { SWIG_PY_INT,     "WIN_OBJ_BASE", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_LABEL", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_WRITE", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_IMAGE", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_CONTAINER", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_SCROLLED", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_SELECT", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_ACTIVATE", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_UNACTIVATE", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_UPDATE", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_DRAW", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_DRAW_ONLY_VISIBLE", (long) 11, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_ACTIVATE_KEY", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_NEXT_KEY", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_PREVIOUS_KEY", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_SCROLL_UP", (long) 7, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_SCROLL_DOWN", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_SELECT", (long) 9, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_UNSELECT", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SELECT_MODE_BRIGHTNESS", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SELECT_MODE_BORDER", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SELECT_MODE_CURSOR", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIZE_NORMAL", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIZE_MINI", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SCROLLBAR_PAD_DEFAULT", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SPACE_BETWEEN_BORDER", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SPACE_BETWEEN_OBJECT", (long) 5, 0, 0, 0},
{0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initwin_labelc(void) {
    PyObject *m, *d;
    int i;
    SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule("win_labelc", win_labelcMethods);
    d = PyModule_GetDict(m);
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    SWIG_InstallConstants(d,swig_const_table);
}

