/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3u-20001216-1131 (Alpha 5)
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGPYTHON
/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/

#include <string.h>

#if defined(_WIN32) || defined(__WIN32__)
#       if defined(_MSC_VER)
#               if defined(STATIC_LINKED)
#                       define SWIGEXPORT(a) a
#               else
#                       define SWIGEXPORT(a) __declspec(dllexport) a
#               endif
#       else
#               if defined(__BORLANDC__)
#                       define SWIGEXPORT(a) a _export
#               else
#                       define SWIGEXPORT(a) a
#       endif
#endif
#else
#       define SWIGEXPORT(a) a
#endif

#ifdef SWIG_GLOBAL
#define SWIGRUNTIME(a) SWIGEXPORT(a)
#else
#define SWIGRUNTIME(a) static a
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct swig_type_info {
  char  *name;                 
  void *(*converter)(void *);
  char  *str;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

#ifdef SWIG_NOINCLUDE
SWIGEXPORT(swig_type_info *) SWIG_TypeRegister(swig_type_info *);
SWIGEXPORT(swig_type_info *) SWIG_TypeCheck(char *c, swig_type_info *);
SWIGEXPORT(void *) SWIG_TypeCast(swig_type_info *, void *);
#else

static swig_type_info *swig_type_list = 0;

/* Register a type mapping with the type-checking */
SWIGRUNTIME(swig_type_info *)
SWIG_TypeRegister(swig_type_info *ti)
{
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = swig_type_list;
  while (tc) {
    if (strcmp(tc->name, ti->name) == 0) {
      /* Already exists in the table.  Just add additional types to the list */
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = swig_type_list;
  swig_type_list = ti;

  /* Build linked lists */
 l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  head->next = next;
  return ret;
}

/* Check the typename */
SWIGRUNTIME(swig_type_info *) 
SWIG_TypeCheck(char *c, swig_type_info *ty)
{
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  while (s) {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
	s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      return s;
    }
    s = s->next;
  }
  return 0;
}

/* Cast a pointer (needed for C++ inheritance */
SWIGRUNTIME(void *) 
SWIG_TypeCast(swig_type_info *ty, void *ptr) 
{
  if ((!ty) || (!ty->converter)) return ptr;
  return (*ty->converter)(ptr);
}

/* Search for a swig_type_info structure */
SWIGRUNTIME(void *)
SWIG_TypeQuery(const char *name) {
  swig_type_info *ty = swig_type_list;
  while (ty) {
    if (ty->str && (strcmp(name,ty->str) == 0)) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

#endif

#ifdef __cplusplus
}
#endif



/***********************************************************************
 * python.swg
 *
 *     This file contains the runtime support for Python modules
 *     and includes code for managing global variables and pointer
 *     type checking.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 ************************************************************************/

#include <stdlib.h>
#include "Python.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SWIG_PY_INT     1
#define SWIG_PY_FLOAT   2
#define SWIG_PY_STRING  3
#define SWIG_PY_POINTER 4

/* Constant information structure */
typedef struct swig_const_info {
    int type;
    char *name;
    long lvalue;
    double dvalue;
    void   *pvalue;
    swig_type_info **ptype;
} swig_const_info;

#ifdef SWIG_NOINCLUDE

SWIGEXPORT(PyObject *)        SWIG_newvarlink();
SWIGEXPORT(void)              SWIG_addvarlink(PyObject *, char *, PyObject *(*)(void), int (*)(PyObject *));
SWIGEXPORT(int)               SWIG_ConvertPtr(PyObject *, void **, swig_type_info *, int);
SWIGEXPORT(void)              SWIG_MakePtr(char *c, void *, swig_type_info *);
SWIGEXPORT(PyObject *)        SWIG_NewPointerObj(void *, swig_type_info *);
SWIGEXPORT(void)              SWIG_InstallConstants(PyObject *d, swig_const_info constants[]);

#else

/* -----------------------------------------------------------------------------
 * global variable support code.
 * ----------------------------------------------------------------------------- */

typedef struct swig_globalvar {   
  char       *name;                  /* Name of global variable */
  PyObject *(*get_attr)(void);       /* Return the current value */
  int       (*set_attr)(PyObject *); /* Set the value */
  struct swig_globalvar *next;
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar *vars;
} swig_varlinkobject;

static PyObject *
swig_varlink_repr(swig_varlinkobject *v) {
  v = v;
  return PyString_FromString("<Global variables>");
}

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags) {
  swig_globalvar  *var;
  flags = flags;
  fprintf(fp,"Global variables { ");
  for (var = v->vars; var; var=var->next) {
    fprintf(fp,"%s", var->name);
    if (var->next) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->get_attr)();
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return NULL;
}

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p) {
  swig_globalvar *var = v->vars;
  while (var) {
    if (strcmp(var->name,n) == 0) {
      return (*var->set_attr)(p);
    }
    var = var->next;
  }
  PyErr_SetString(PyExc_NameError,"Unknown C global variable");
  return 1;
}

statichere PyTypeObject varlinktype = {
  PyObject_HEAD_INIT(0)              
  0,
  "swigvarlink",                      /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */
SWIGRUNTIME(PyObject *)
SWIG_newvarlink(void) {
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  result->vars = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGRUNTIME(void)
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p)) {
  swig_varlinkobject *v;
  swig_globalvar *gv;
  v= (swig_varlinkobject *) p;
  gv = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  gv->name = (char *) malloc(strlen(name)+1);
  strcpy(gv->name,name);
  gv->get_attr = get_attr;
  gv->set_attr = set_attr;
  gv->next = v->vars;
  v->vars = gv;
}
/* Convert a pointer value */
SWIGRUNTIME(int)
SWIG_ConvertPtr(PyObject *obj, void **ptr, swig_type_info *ty, int flags) {
  unsigned long p;
  register int d;
  swig_type_info *tc;
  char  *c;
  static PyObject *SWIG_this = 0;
  int    newref = 0;

  if (!obj || (obj == Py_None)) {
    *ptr = 0;
    return 0;
  }
#ifdef SWIG_COBJECT_TYPES
  if (!(PyCObject_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyCObject_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  *ptr = PyCObject_AsVoidPtr(obj);
  c = (char *) PyCObject_GetDesc(obj);
  if (newref) Py_DECREF(obj);
  goto cobject;
#else
  if (!(PyString_Check(obj))) {
    if (!SWIG_this)
      SWIG_this = PyString_InternFromString("this");
    obj = PyObject_GetAttr(obj,SWIG_this);
    newref = 1;
    if (!obj) goto type_error;
    if (!PyString_Check(obj)) {
      Py_DECREF(obj);
      goto type_error;
    }
  } 
  c = PyString_AsString(obj);
  p = 0;
  /* Pointer values must start with leading underscore */
  if (*c != '_') {
    *ptr = (void *) 0;
    if (strcmp(c,"NULL") == 0) {
      if (newref) Py_DECREF(obj);
      return 0;
    } else {
      if (newref) Py_DECREF(obj);
      goto type_error;
    }
  }
  c++;
  /* Extract hex value from pointer */
  while ((d = *c)) {
    if ((d >= '0') && (d <= '9'))
      p = (p << 4) + (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      p = (p << 4) + (d - ('a'-10));
    else
      break; 
    c++;
  }
  *ptr = (void *) p;
  if (newref) Py_DECREF(obj);
#endif

#ifdef SWIG_COBJECT_TYPES
cobject:
#endif

  if (ty) {
    tc = SWIG_TypeCheck(c,ty);
    if (!tc) goto type_error;
    *ptr = SWIG_TypeCast(tc,(void*)p);
  }
  return 0;

type_error:

  if (flags) {
    if (ty) {
      char *temp = (char *) malloc(64+strlen(ty->name));
      sprintf(temp,"Type error. Expected %s", ty->name);
      PyErr_SetString(PyExc_TypeError, temp);
      free((char *) temp);
    } else {
      PyErr_SetString(PyExc_TypeError,"Expected a pointer");
    }
  }
  return -1;
}

/* Take a pointer and convert it to a string */
SWIGRUNTIME(void) 
SWIG_MakePtr(char *c, void *ptr, swig_type_info *ty) {
  static char hex[17] = "0123456789abcdef";
  unsigned long p, s;
  char result[32], *r; 
  r = result;
  p = (unsigned long) ptr;
  if (p > 0) {
    while (p > 0) {
      s = p & 0xf;
      *(r++) = hex[s];
      p = p >> 4;
    }
    *r = '_';
    while (r >= result)
      *(c++) = *(r--);
    strcpy (c, ty->name);
  } else {
    strcpy (c, "NULL");
  }
}

/* Create a new pointer object */
SWIGRUNTIME(PyObject *)
SWIG_NewPointerObj(void *ptr, swig_type_info *type) {
  char result[512];
  PyObject *robj;
  if (!ptr) {
    Py_INCREF(Py_None);
    return Py_None;
  }
#ifdef SWIG_COBJECT_TYPES
  robj = PyCObject_FromVoidPtrAndDesc((void *) ptr, type->name, NULL);
#else
  SWIG_MakePtr(result,ptr,type);
  robj = PyString_FromString(result);
#endif
  return robj;
}

/* Install Constants */
SWIGRUNTIME(void)
SWIG_InstallConstants(PyObject *d, swig_const_info constants[]) {
  int i;
  PyObject *obj;
  for (i = 0; constants[i].type; i++) {
    switch(constants[i].type) {
    case SWIG_PY_INT:
      obj = PyInt_FromLong(constants[i].lvalue);
      break;
    case SWIG_PY_FLOAT:
      obj = PyFloat_FromDouble(constants[i].dvalue);
      break;
    case SWIG_PY_STRING:
      obj = PyString_FromString((char *) constants[i].pvalue);
      break;
    case SWIG_PY_POINTER:
      obj = SWIG_NewPointerObj(constants[i].pvalue, *(constants[i]).ptype);
      break;
    default:
      obj = 0;
      break;
    }
    if (obj) {
      PyDict_SetItemString(d,constants[i].name,obj);
      Py_DECREF(obj);
    }
  }
}

#endif

#ifdef __cplusplus
}
#endif



/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_win_font swig_types[0] 
#define  SWIGTYPE_p_image swig_types[1] 
static swig_type_info *swig_types[3];

/* -------- TYPES TABLE (END) -------- */


/*-----------------------------------------------
              @(target):= win_fontc.so
  ------------------------------------------------*/
#define SWIG_init    initwin_fontc

#define SWIG_name    "win_fontc"


#include "win_types.h"
#include "win_base.h"
#include "win_font.h"

#ifdef __cplusplus
extern "C" {
#endif
static PyObject *_wrap_new_win_font(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    char *arg0 ;
    win_font *result ;
    
    if(!PyArg_ParseTuple(args,"s:new_win_font",&arg0)) return NULL;
    result = (win_font *)new win_font(arg0);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_win_font);
    return resultobj;
}


static PyObject *_wrap_delete_win_font(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"O:delete_win_font",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    delete arg0;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_font_load(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    char *arg1 ;
    PyObject * argo0 =0 ;
    
    if(!PyArg_ParseTuple(args,"Os:win_font_load",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    arg0->load(arg1);
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_font_in_table(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    unsigned short arg1 ;
    PyObject * argo0 =0 ;
    bool result ;
    
    if(!PyArg_ParseTuple(args,"Oh:win_font_in_table",&argo0,&arg1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    result = (bool )arg0->in_table(arg1);
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_font_height(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:win_font_height",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    result = (unsigned short )arg0->height();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_font_length(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    PyObject * argo0 =0 ;
    unsigned short result ;
    
    if(!PyArg_ParseTuple(args,"O:win_font_length",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    result = (unsigned short )arg0->length();
    resultobj = PyInt_FromLong((long)result);
    return resultobj;
}


static PyObject *_wrap_win_font_cursor_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    image *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:win_font_cursor_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_image,1)) == -1) return NULL;
    arg0->cursor = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_font_cursor_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    PyObject * argo0 =0 ;
    image *result ;
    
    if(!PyArg_ParseTuple(args,"O:win_font_cursor_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    result = (image *) (arg0->cursor);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_image);
    return resultobj;
}


static PyObject *_wrap_win_font_table_set(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    image *arg1 ;
    PyObject * argo0 =0 ;
    PyObject * argo1 =0 ;
    
    if(!PyArg_ParseTuple(args,"OO:win_font_table_set",&argo0,&argo1)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    if ((SWIG_ConvertPtr(argo1,(void **) &arg1,SWIGTYPE_p_image,1)) == -1) return NULL;
    arg0->table = arg1;
    Py_INCREF(Py_None);
    resultobj = Py_None;
    return resultobj;
}


static PyObject *_wrap_win_font_table_get(PyObject *self, PyObject *args) {
    PyObject *resultobj;
    win_font *arg0 ;
    PyObject * argo0 =0 ;
    image *result ;
    
    if(!PyArg_ParseTuple(args,"O:win_font_table_get",&argo0)) return NULL;
    if ((SWIG_ConvertPtr(argo0,(void **) &arg0,SWIGTYPE_p_win_font,1)) == -1) return NULL;
    result = (image *) (arg0->table);
    resultobj = SWIG_NewPointerObj((void *) result, SWIGTYPE_p_image);
    return resultobj;
}


static PyMethodDef win_fontcMethods[] = {
	 { "new_win_font", _wrap_new_win_font, METH_VARARGS },
	 { "delete_win_font", _wrap_delete_win_font, METH_VARARGS },
	 { "win_font_load", _wrap_win_font_load, METH_VARARGS },
	 { "win_font_in_table", _wrap_win_font_in_table, METH_VARARGS },
	 { "win_font_height", _wrap_win_font_height, METH_VARARGS },
	 { "win_font_length", _wrap_win_font_length, METH_VARARGS },
	 { "win_font_cursor_set", _wrap_win_font_cursor_set, METH_VARARGS },
	 { "win_font_cursor_get", _wrap_win_font_cursor_get, METH_VARARGS },
	 { "win_font_table_set", _wrap_win_font_table_set, METH_VARARGS },
	 { "win_font_table_get", _wrap_win_font_table_get, METH_VARARGS },
	 { NULL, NULL }
};

#ifdef __cplusplus
}
#endif

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_win_font[] = {{"_p_win_font", 0, "win_font *"},{"_p_win_font"},{0}};
static swig_type_info _swigt__p_image[] = {{"_p_image", 0, "image *"},{"_p_image"},{0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_win_font, 
_swigt__p_image, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

static swig_const_info swig_const_table[] = {
    { SWIG_PY_INT,     "WIN_NB_TABLE_CHAR", (long) 255, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_TEXT_MAX_LENGTH", (long) 5000, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_FONT_HEIGHT", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_FONT_LENGHT", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SPACE_LENGHT", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_JUSTIFY_LEFT", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_JUSTIFY_RIGHT", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_JUSTIFY_CENTER", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_JUSTIFY_NO", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_LAYOUT_NO", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_LAYOUT_LIST", (long) 1, 0, 0, 0},
    { SWIG_PY_STRING, "WIN_DIRECTORY", 0, 0, (void *) "gfxtree/window/", 0 }, 
    { SWIG_PY_STRING, "WIN_FONT_DIRECTORY", 0, 0, (void *) "font/", 0 }, 
    { SWIG_PY_STRING, "WIN_BORDER_DIRECTORY", 0, 0, (void *) "border/", 0 }, 
    { SWIG_PY_STRING, "WIN_BACKGROUND_DIRECTORY", 0, 0, (void *) "background/", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_DIRECTORY", 0, 0, (void *) "scrollbar/", 0 }, 
    { SWIG_PY_STRING, "WIN_CURSOR_DIRECTORY", 0, 0, (void *) "cursor/", 0 }, 
    { SWIG_PY_STRING, "WIN_FONT_FILE_IDX", 0, 0, (void *) "font.idx", 0 }, 
    { SWIG_PY_STRING, "WIN_FONT_FILE_PIC", 0, 0, (void *) "font.pnm", 0 }, 
    { SWIG_PY_INT,     "WIN_CURSOR_BLINKING", (long) 75, 0, 0, 0},
    { SWIG_PY_STRING, "WIN_V_BORDER_TEMPLATE_FILE", 0, 0, (void *) "v_border.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_H_BORDER_TEMPLATE_FILE", 0, 0, (void *) "h_border.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CORNER_TOP_LEFT_FILE", 0, 0, (void *) "corner_top_left.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CORNER_TOP_RIGHT_FILE", 0, 0, (void *) "corner_top_right.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CORNER_BOTTOM_LEFT_FILE", 0, 0, (void *) "corner_bottom_left.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CORNER_BOTTOM_RIGHT_FILE", 0, 0, (void *) "corner_bottom_right.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_BACKGROUND_FILE", 0, 0, (void *) "background.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BAR_TOP", 0, 0, (void *) "scroll_bar_top.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BAR_MID", 0, 0, (void *) "scroll_bar_mid.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BAR_BOT", 0, 0, (void *) "scroll_bar_bot.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BAR_FLEX", 0, 0, (void *) "scroll_bar_flex.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BACK_TOP", 0, 0, (void *) "scroll_back_top.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BACK_MID", 0, 0, (void *) "scroll_back_mid.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_SCROLLBAR_BACK_BOT", 0, 0, (void *) "scroll_back_bot.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_CURSOR_FILE", 0, 0, (void *) "cursor.pnm", 0 }, 
    { SWIG_PY_STRING, "WIN_BORDER_NORMAL_SIZE", 0, 0, (void *) "normal/", 0 }, 
    { SWIG_PY_STRING, "WIN_BORDER_MINI_SIZE", 0, 0, (void *) "mini/", 0 }, 
    { SWIG_PY_STRING, "WIN_THEME_ORIGINAL", 0, 0, (void *) "original/", 0 }, 
    { SWIG_PY_STRING, "WIN_THEME_ELFE", 0, 0, (void *) "silverleaf/", 0 }, 
    { SWIG_PY_INT,     "WIN_OBJ_BASE", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_LABEL", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_WRITE", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_IMAGE", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_CONTAINER", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_SCROLLED", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_OBJ_SELECT", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_ACTIVATE", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_UNACTIVATE", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_UPDATE", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_DRAW", (long) 3, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_DRAW_ONLY_VISIBLE", (long) 11, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_ACTIVATE_KEY", (long) 4, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_NEXT_KEY", (long) 5, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_PREVIOUS_KEY", (long) 6, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_SCROLL_UP", (long) 7, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_SCROLL_DOWN", (long) 8, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_SELECT", (long) 9, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIG_UNSELECT", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SELECT_MODE_BRIGHTNESS", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SELECT_MODE_BORDER", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SELECT_MODE_CURSOR", (long) 2, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIZE_NORMAL", (long) 0, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SIZE_MINI", (long) 1, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SCROLLBAR_PAD_DEFAULT", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SPACE_BETWEEN_BORDER", (long) 10, 0, 0, 0},
    { SWIG_PY_INT,     "WIN_SPACE_BETWEEN_OBJECT", (long) 5, 0, 0, 0},
{0}};

static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void) initwin_fontc(void) {
    PyObject *m, *d;
    int i;
    SWIG_globals = SWIG_newvarlink();
    m = Py_InitModule("win_fontc", win_fontcMethods);
    d = PyModule_GetDict(m);
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
    }
    SWIG_InstallConstants(d,swig_const_table);
}

